apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdt-dev
  template:
    metadata:
      labels:
        app: tdt-dev
    spec:
      containers:
      - name: tdt-dev
        image: tdt-dev.azurecr.io/tdt-dev:latest
        ports:
        - containerPort: 5000

        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: appinsights-secret
              key: APPLICATIONINSIGHTS_CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: tdt-dev-service
spec:
  type: LoadBalancer
  selector:
    app: tdt-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

