apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdt-dev
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  selector:
    matchLabels:
      app: tdt-dev

  template:
    metadata:
      labels:
        app: tdt-dev

    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

      containers:
      - name: tdt-dev
        image: tdtrackeracr.azurecr.io/technical-debt-tracker:21
        imagePullPolicy: Always
        
        ports:
        - containerPort: 5000

        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: appinsights-secret
              key: APPLICATIONINSIGHTS_CONNECTION_STRING

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: SECRET_KEY

        volumeMounts:
        - name: sqlite-storage
          mountPath: /app/instance

      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tdt-dev-service
spec:
  type: LoadBalancer
  selector:
    app: tdt-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

