FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-dev.txt

CMD ["python", "--version"]